modLoader="kotlinforforge"
loaderVersion="[1.12,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "endless"
version = "${version}"
displayName = "Endless"
authors = "ReMod Studios"
description = '''
An End Expansion aiming to add more wackyness to the End Dimension!
'''
#logoFile = ""

[[dependencies.endless]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endless]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

